services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: expert-call-ai-backend

    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}

    ports:
      - "8000:8000"

    volumes:
      - ./backend/vectorstore:/app/vectorstore

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: expert-call-ai-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    restart: unless-stopped